name: Openwrt Build Bot for 22.03
on:
  push:
    branches: main
    paths:
      - '**'
      - '!README.md'
      - '!.gitignore'
      - '!.github/workflows/build-release-21.02.yml'
      - '!.github/workflows/build-snapshot.yml'
      - '!.github/workflows/build-immortalwrt-snapshot.yml'
      - '!fetch.sh'
      - '!build.sh'
  schedule:
  - cron: 0 17 * * 5

jobs:
  buildpkg:
    name: Build Openwrt Package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x86_64-22.03.3

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare feeds
        run: |
          chmod +x fetch.sh && ./fetch.sh

      - name: Build 
        uses: openwrt/gh-action-sdk@v5.4
        env:
          ARCH: ${{ matrix.arch }}
          KEY_BUILD: ${{ secrets.KEY_BUILD }}
          INDEX: 0
          IGNORE_ERRORS: 1
          PACKAGES: |
            luabitop
            luci-app-tn-netports
            luci-app-temp-status

      - name: List files
        run: |
          ls -R bin/

      - name: Upload
        env:
          ARCH: ${{ matrix.arch }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          BRANCH="packages/${ARCH::-2}"
          if [[ $ARCH =~ "snapshot" ]]; then
              BRANCH="packages/$ARCH"
          fi
          cd bin/packages/*/action
          sudo chown runner:runner -R .
          git init
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add .
          git commit -m "$(TZ='Asia/Shanghai' date +@%Y%m%d)"
          git push --force --quiet "https://$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY" HEAD:$BRANCH
